tap "aws/tap"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"

brew "readline", link: true
brew "awscli"
brew "bat"
brew "direnv"
brew "fzf"
brew "jq"
brew "peco"
brew "pstree"
brew "ruby-build"
brew "rbenv"
brew "ripgrep"
brew "the_silver_searcher"
brew "tig"
brew "tmux"
brew "tree"
brew "vim"
brew "wget"
brew "aws/tap/aws-sam-cli"

cask "chromedriver"
cask "ngrok"
